// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using liaqati_master.Data;

#nullable disable

namespace liaqati_master.Migrations
{
    [DbContext(typeof(LiaqatiDBContext))]
    [Migration("20230314171959_Database")]
    partial class Database
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("liaqati_master.Models.Achievements", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("File")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("liaqati_master.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewsNumber")
                        .HasColumnType("int");

                    b.Property<int>("likesNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("TblArticles");
                });

            modelBuilder.Entity("liaqati_master.Models.AthleticProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BodyFocus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Equipment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("servicesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("servicesId")
                        .IsUnique()
                        .HasFilter("[servicesId] IS NOT NULL");

                    b.ToTable("TblSportsProgram");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BodyFocus = "كل الجسم",
                            Description = "<p>\n أفضل طريقة لتحصيل أفضل النتائج من جهودك في التدريب هي تطبيق عدّة طرق وأنواع من التمارين والروتينات, وذلك لتمنح جسمك حوافز جديدة باستمرار لنمو العضلات وبناء أنسجة عضلية جديدة, ولتمنع تأقلم جسمك مع التدريبات التي تمارسهاء فإذا حصل هذا التاقلم سيبطئ عملية حرق الدهون وبناء العضلات. لذا عليك تغيير روتين تدريبك باستمرارإن كنت قد اتخذت قرارك بوضع حد لجسمك المترهّل وأسلوب حياتك الخامل وتريد أن تعرف كيف تنفذ خطة تدربيبة تعطيك نتائج مذهلة في فترة قصيرة, فقد وصلت للمكان المناسب. ستمكّنك هذه الخطة من رؤية تغيّرات جذرية في انسيابية جسمك ورشاقتك ومستوى لياقتك البدنية خلال 8 أسابيع من تنفيذها</p><h2>why kadljkd</h2>",
                            Difficulty = "3-4",
                            Equipment = "حزام التمرين,سجاد",
                            Length = 8,
                            Price = 99.0,
                            Title = " برنامج لنحت وتفصيل الجسم في 8 أسابيع فقط",
                            TrainingType = "القلب والأوعية الدموية ، تأثير منخفض ، تدريب القوة ، التنغيم ، اليوجا ، الحركة"
                        });
                });

            modelBuilder.Entity("liaqati_master.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("target")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("liaqati_master.Models.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ReceiverID")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Chat");
                });

            modelBuilder.Entity("liaqati_master.Models.ChatUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatUser");
                });

            modelBuilder.Entity("liaqati_master.Models.Comment_Servies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("commentFor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("repliedFor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("servicesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("servicesId");

                    b.ToTable("Comment_Servies");
                });

            modelBuilder.Entity("liaqati_master.Models.Comments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("articlesId")
                        .HasColumnType("int");

                    b.Property<string>("commentFor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("repliedFor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("articlesId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("liaqati_master.Models.Exercies_program", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("exerciseId")
                        .HasColumnType("int");

                    b.Property<bool>("isComplete")
                        .HasColumnType("bit");

                    b.Property<int?>("sportsProgramId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("exerciseId");

                    b.HasIndex("sportsProgramId");

                    b.ToTable("Exercies_program");
                });

            modelBuilder.Entity("liaqati_master.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("DEx")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Equipments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TraningType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TblExercises");
                });

            modelBuilder.Entity("liaqati_master.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Favorite");
                });

            modelBuilder.Entity("liaqati_master.Models.Favorite_Servies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("favoriteId")
                        .HasColumnType("int");

                    b.Property<int?>("servicesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("favoriteId");

                    b.HasIndex("servicesId");

                    b.ToTable("Favorite_Servies");
                });

            modelBuilder.Entity("liaqati_master.Models.HealthyRecipes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<int>("DieteryType")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.Property<int>("Protein")
                        .HasColumnType("int");

                    b.Property<int>("Total_Carbohydrate")
                        .HasColumnType("int");

                    b.Property<DateTime>("prepTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("servicesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("servicesId")
                        .IsUnique()
                        .HasFilter("[servicesId] IS NOT NULL");

                    b.ToTable("HealthyRecipes");
                });

            modelBuilder.Entity("liaqati_master.Models.MealPlans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<double>("avgRecipeTime")
                        .HasColumnType("float");

                    b.Property<string>("dietaryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mealType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("servicesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("servicesId")
                        .IsUnique()
                        .HasFilter("[servicesId] IS NOT NULL");

                    b.ToTable("TblMealPlans");
                });

            modelBuilder.Entity("liaqati_master.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("liaqati_master.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("OrderDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserIdDelivery")
                        .HasColumnType("int");

                    b.Property<int>("UserIdResiver")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TblOrder");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 0.0,
                            UserId = 1,
                            UserIdDelivery = 1,
                            UserIdResiver = 1
                        });
                });

            modelBuilder.Entity("liaqati_master.Models.Order_Details", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("RateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("TblOrder_Details");
                });

            modelBuilder.Entity("liaqati_master.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<string>("Pname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("imgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("servicesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("servicesId")
                        .IsUnique()
                        .HasFilter("[servicesId] IS NOT NULL");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("liaqati_master.Models.Rate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Order_DetailsId")
                        .HasColumnType("int");

                    b.Property<int>("review")
                        .HasColumnType("int");

                    b.Property<DateTime>("review_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Order_DetailsId")
                        .IsUnique()
                        .HasFilter("[Order_DetailsId] IS NOT NULL");

                    b.ToTable("TblRate");
                });

            modelBuilder.Entity("liaqati_master.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HealthyRecipesId")
                        .HasColumnType("int");

                    b.Property<int?>("MealPlansId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("ProductsId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("sportsProgramId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("TblServices");
                });

            modelBuilder.Entity("liaqati_master.Models.Trak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("servicesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("servicesId");

                    b.ToTable("Trak");
                });

            modelBuilder.Entity("liaqati_master.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Cover_photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Exp_Years")
                        .HasColumnType("int");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Photograph")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wieght")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = false,
                            Cover_photo = "sssssssssssssssa",
                            Exp_Years = 10,
                            Fname = "sssssssssssssss",
                            Gender = 1,
                            Height = 120,
                            Lname = "sssssssssssssss",
                            Photograph = "ssssssssssssssss",
                            Wieght = 120
                        });
                });

            modelBuilder.Entity("liaqati_master.Models.Achievements", b =>
                {
                    b.HasOne("liaqati_master.Models.User", "User")
                        .WithMany("Achievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("liaqati_master.Models.Article", b =>
                {
                    b.HasOne("liaqati_master.Models.Category", "Category")
                        .WithMany("articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("liaqati_master.Models.AthleticProgram", b =>
                {
                    b.HasOne("liaqati_master.Models.Service", "services")
                        .WithOne("sportsProgram")
                        .HasForeignKey("liaqati_master.Models.AthleticProgram", "servicesId");

                    b.Navigation("services");
                });

            modelBuilder.Entity("liaqati_master.Models.ChatUser", b =>
                {
                    b.HasOne("liaqati_master.Models.Chat", "Chat")
                        .WithMany("ChatUser")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("liaqati_master.Models.User", "User")
                        .WithMany("ChatUser")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("liaqati_master.Models.Comment_Servies", b =>
                {
                    b.HasOne("liaqati_master.Models.Service", "services")
                        .WithMany("commentServies")
                        .HasForeignKey("servicesId");

                    b.Navigation("services");
                });

            modelBuilder.Entity("liaqati_master.Models.Comments", b =>
                {
                    b.HasOne("liaqati_master.Models.Article", "articles")
                        .WithMany("comments")
                        .HasForeignKey("articlesId");

                    b.Navigation("articles");
                });

            modelBuilder.Entity("liaqati_master.Models.Exercies_program", b =>
                {
                    b.HasOne("liaqati_master.Models.Exercise", "exercise")
                        .WithMany("exercies_Programs")
                        .HasForeignKey("exerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("liaqati_master.Models.AthleticProgram", "sportsProgram")
                        .WithMany("exercies_Programs")
                        .HasForeignKey("sportsProgramId");

                    b.Navigation("exercise");

                    b.Navigation("sportsProgram");
                });

            modelBuilder.Entity("liaqati_master.Models.Favorite_Servies", b =>
                {
                    b.HasOne("liaqati_master.Models.Favorite", "favorite")
                        .WithMany("Favorite_Servies")
                        .HasForeignKey("favoriteId");

                    b.HasOne("liaqati_master.Models.Service", "services")
                        .WithMany("favorites")
                        .HasForeignKey("servicesId");

                    b.Navigation("favorite");

                    b.Navigation("services");
                });

            modelBuilder.Entity("liaqati_master.Models.HealthyRecipes", b =>
                {
                    b.HasOne("liaqati_master.Models.Service", "services")
                        .WithOne("HealthyRecipes")
                        .HasForeignKey("liaqati_master.Models.HealthyRecipes", "servicesId");

                    b.Navigation("services");
                });

            modelBuilder.Entity("liaqati_master.Models.MealPlans", b =>
                {
                    b.HasOne("liaqati_master.Models.Service", "services")
                        .WithOne("MealPlans")
                        .HasForeignKey("liaqati_master.Models.MealPlans", "servicesId");

                    b.Navigation("services");
                });

            modelBuilder.Entity("liaqati_master.Models.Message", b =>
                {
                    b.HasOne("liaqati_master.Models.Chat", "Chat")
                        .WithMany("Message")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("liaqati_master.Models.Order", b =>
                {
                    b.HasOne("liaqati_master.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("liaqati_master.Models.Order_Details", b =>
                {
                    b.HasOne("liaqati_master.Models.Order", "Order")
                        .WithMany("Order_Details")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("liaqati_master.Models.Products", b =>
                {
                    b.HasOne("liaqati_master.Models.Service", "services")
                        .WithOne("Products")
                        .HasForeignKey("liaqati_master.Models.Products", "servicesId");

                    b.Navigation("services");
                });

            modelBuilder.Entity("liaqati_master.Models.Rate", b =>
                {
                    b.HasOne("liaqati_master.Models.Order_Details", "Order_Details")
                        .WithOne("Rate")
                        .HasForeignKey("liaqati_master.Models.Rate", "Order_DetailsId");

                    b.Navigation("Order_Details");
                });

            modelBuilder.Entity("liaqati_master.Models.Service", b =>
                {
                    b.HasOne("liaqati_master.Models.Category", "Category")
                        .WithMany("services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("liaqati_master.Models.Trak", b =>
                {
                    b.HasOne("liaqati_master.Models.Service", "services")
                        .WithMany("traks")
                        .HasForeignKey("servicesId");

                    b.Navigation("services");
                });

            modelBuilder.Entity("liaqati_master.Models.Article", b =>
                {
                    b.Navigation("comments");
                });

            modelBuilder.Entity("liaqati_master.Models.AthleticProgram", b =>
                {
                    b.Navigation("exercies_Programs");
                });

            modelBuilder.Entity("liaqati_master.Models.Category", b =>
                {
                    b.Navigation("articles");

                    b.Navigation("services");
                });

            modelBuilder.Entity("liaqati_master.Models.Chat", b =>
                {
                    b.Navigation("ChatUser");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("liaqati_master.Models.Exercise", b =>
                {
                    b.Navigation("exercies_Programs");
                });

            modelBuilder.Entity("liaqati_master.Models.Favorite", b =>
                {
                    b.Navigation("Favorite_Servies");
                });

            modelBuilder.Entity("liaqati_master.Models.Order", b =>
                {
                    b.Navigation("Order_Details");
                });

            modelBuilder.Entity("liaqati_master.Models.Order_Details", b =>
                {
                    b.Navigation("Rate");
                });

            modelBuilder.Entity("liaqati_master.Models.Service", b =>
                {
                    b.Navigation("HealthyRecipes");

                    b.Navigation("MealPlans");

                    b.Navigation("Products");

                    b.Navigation("commentServies");

                    b.Navigation("favorites");

                    b.Navigation("sportsProgram");

                    b.Navigation("traks");
                });

            modelBuilder.Entity("liaqati_master.Models.User", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("ChatUser");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
