// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using liaqati_master.Data;

#nullable disable

namespace liaqati_master.Migrations
{
    [DbContext(typeof(LiaqatiDBContext))]
    partial class LiaqatiDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("liaqati_master.Models.Achievements", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TblAchievements");
                });

            modelBuilder.Entity("liaqati_master.Models.Article", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LikesNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewsNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("TblArticles");
                });

            modelBuilder.Entity("liaqati_master.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Target")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "النظام الغذائي"
                        },
                        new
                        {
                            Id = "2",
                            Name = "الوجبات"
                        },
                        new
                        {
                            Id = "3",
                            Name = "المكملات الغذائية"
                        },
                        new
                        {
                            Id = "4",
                            Name = "الاجهزة الرياضية"
                        });
                });

            modelBuilder.Entity("liaqati_master.Models.Chat", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ReceiverID")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Chat");
                });

            modelBuilder.Entity("liaqati_master.Models.ChatUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatUser");
                });

            modelBuilder.Entity("liaqati_master.Models.Comment_Servies", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("commentFor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("repliedFor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("servicesId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("servicesId");

                    b.ToTable("Comment_Servies");
                });

            modelBuilder.Entity("liaqati_master.Models.Comments", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("articlesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("commentFor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("repliedFor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("articlesId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("liaqati_master.Models.Exercies_program", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("exerciseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("isComplete")
                        .HasColumnType("bit");

                    b.Property<string>("sportsProgramId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("exerciseId");

                    b.HasIndex("sportsProgramId");

                    b.ToTable("Exercies_program");
                });

            modelBuilder.Entity("liaqati_master.Models.Exercise", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("DEx")
                        .HasColumnType("int");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Equipments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TraningType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TblExercises");
                });

            modelBuilder.Entity("liaqati_master.Models.Favorite", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Favorite");
                });

            modelBuilder.Entity("liaqati_master.Models.Favorite_Servies", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("favoriteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("servicesId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("servicesId1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("favoriteId");

                    b.HasIndex("servicesId1");

                    b.ToTable("Favorite_Servies");
                });

            modelBuilder.Entity("liaqati_master.Models.HealthyRecipes", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<int>("DieteryType")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MealType")
                        .HasColumnType("int");

                    b.Property<string>("PreparationMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Protein")
                        .HasColumnType("int");

                    b.Property<int>("Total_Carbohydrate")
                        .HasColumnType("int");

                    b.Property<DateTime>("prepTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HealthyRecipes");
                });

            modelBuilder.Entity("liaqati_master.Models.MealPlans", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Length")
                        .HasColumnType("int");

                    b.Property<double?>("avgRecipeTime")
                        .HasColumnType("float");

                    b.Property<string>("dietaryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mealType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("numsubscribers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TblMealPlans");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Length = 0,
                            avgRecipeTime = 0.0,
                            dietaryType = "",
                            image = "",
                            mealType = "",
                            numsubscribers = 0
                        },
                        new
                        {
                            Id = "2",
                            Length = 0,
                            avgRecipeTime = 0.0,
                            dietaryType = "",
                            image = "",
                            mealType = "",
                            numsubscribers = 0
                        },
                        new
                        {
                            Id = "3",
                            Length = 0,
                            avgRecipeTime = 0.0,
                            dietaryType = "",
                            image = "",
                            mealType = "",
                            numsubscribers = 0
                        },
                        new
                        {
                            Id = "4",
                            Length = 0,
                            avgRecipeTime = 0.0,
                            dietaryType = "",
                            image = "",
                            mealType = "",
                            numsubscribers = 0
                        },
                        new
                        {
                            Id = "5",
                            Length = 0,
                            avgRecipeTime = 0.0,
                            dietaryType = "",
                            image = "",
                            mealType = "",
                            numsubscribers = 0
                        });
                });

            modelBuilder.Entity("liaqati_master.Models.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("liaqati_master.Models.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("OrderDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserIdDelivery")
                        .HasColumnType("int");

                    b.Property<int>("UserIdResiver")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TblOrder");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 0.0,
                            UserId = "1",
                            UserIdDelivery = 1,
                            UserIdResiver = 1
                        });
                });

            modelBuilder.Entity("liaqati_master.Models.Order_Details", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("RateId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("TblOrder_Details");
                });

            modelBuilder.Entity("liaqati_master.Models.Products", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<string>("imgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TblProducts");

                    b.HasData(
                        new
                        {
                            Id = "21",
                            Discount = 20.0,
                            imgUrl = "/Images/Product/Dumbbell3.jfif"
                        },
                        new
                        {
                            Id = "22",
                            Discount = 0.0,
                            imgUrl = "/Images/Product/LiveupOlympic.jpg"
                        },
                        new
                        {
                            Id = "23",
                            Discount = 0.0,
                            imgUrl = "/Images/Product/Curved.jpg"
                        },
                        new
                        {
                            Id = "24",
                            Discount = 0.0,
                            imgUrl = "/Images/Product/Spinner.jpg"
                        },
                        new
                        {
                            Id = "25",
                            Discount = 0.0,
                            imgUrl = "/Images/Product/Liveup.jpg"
                        },
                        new
                        {
                            Id = "26",
                            Discount = 0.0,
                            imgUrl = "/Images/Product/LiveupOlympic.jpg"
                        },
                        new
                        {
                            Id = "27",
                            Discount = 0.0,
                            imgUrl = "/Images/Product/Bowflex.jpg"
                        },
                        new
                        {
                            Id = "28",
                            Discount = 0.0,
                            imgUrl = "/Images/Product/Brobantle.jfif"
                        },
                        new
                        {
                            Id = "29",
                            Discount = 0.0,
                            imgUrl = "/Images/Product/Adjustable.jpg"
                        },
                        new
                        {
                            Id = "30",
                            Discount = 0.0,
                            imgUrl = "/Images/Product/rower.jpg"
                        },
                        new
                        {
                            Id = "31",
                            Discount = 0.0,
                            imgUrl = "/Images/Product/omega.jpg"
                        },
                        new
                        {
                            Id = "32",
                            Discount = 0.0,
                            imgUrl = "/Images/Product/Muscletech.jpg"
                        },
                        new
                        {
                            Id = "33",
                            Discount = 0.0,
                            imgUrl = "/Images/Product/Ultima.jpg"
                        },
                        new
                        {
                            Id = "34",
                            Discount = 0.0,
                            imgUrl = "/Images/Product/krilloil.jpg"
                        },
                        new
                        {
                            Id = "35",
                            Discount = 0.0,
                            imgUrl = "/Images/Product/anavite.jpg"
                        },
                        new
                        {
                            Id = "36",
                            Discount = 0.0,
                            imgUrl = "/Images/Product/Trace.jpg"
                        },
                        new
                        {
                            Id = "37",
                            Discount = 0.0,
                            imgUrl = "/Images/Product/BodyBio.jpg"
                        },
                        new
                        {
                            Id = "38",
                            Discount = 0.0,
                            imgUrl = "/Images/Product/Vega.jpg"
                        },
                        new
                        {
                            Id = "39",
                            Discount = 0.0,
                            imgUrl = "/Images/Product/HydrationMultiplier.jpg"
                        },
                        new
                        {
                            Id = "40",
                            Discount = 0.0,
                            imgUrl = "/Images/Product/NutriBiotic.jpg"
                        },
                        new
                        {
                            Id = "41",
                            Discount = 0.0,
                            imgUrl = "/Images/Product/krilloil.jpg"
                        });
                });

            modelBuilder.Entity("liaqati_master.Models.Rate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Order_DetailsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("review")
                        .HasColumnType("int");

                    b.Property<DateTime>("review_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Order_DetailsId")
                        .IsUnique()
                        .HasFilter("[Order_DetailsId] IS NOT NULL");

                    b.ToTable("TblRate");
                });

            modelBuilder.Entity("liaqati_master.Models.Service", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("TblServices");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            CategoryId = "1",
                            Description = "يعتمد على تناول البقوليات و المكسرات و الأوراق الخضراء ,مفيد لمرضى السكر و القلب ",
                            Price = 19.989999999999998,
                            Title = "حمية البحر المتوسط"
                        },
                        new
                        {
                            Id = "2",
                            CategoryId = "1",
                            Description = " يعتمد على تقليل الكربوهيدرات  و منع السكر المصنع و البطاطا , يتم تناول الفواكه و الخضروات و الحبوب",
                            Price = 20.989999999999998,
                            Title = "  النظام الغذائي باليو"
                        },
                        new
                        {
                            Id = "3",
                            CategoryId = "1",
                            Description = "  يعتمد على تقليل الكربوهيدرات و تناول الدهون الصحية , لا ينصح به النساءو الحوامل و كبار السن",
                            Price = 19.989999999999998,
                            Title = "   كيتو دايت "
                        },
                        new
                        {
                            Id = "4",
                            CategoryId = "1",
                            Description = "  يعتمد على تقليل الكربوهيدرات و تناول الدهون الصحية , لا ينصح به النساءو الحوامل و كبار السن",
                            Price = 19.989999999999998,
                            Title = "   كيتو دايت "
                        },
                        new
                        {
                            Id = "5",
                            CategoryId = "1",
                            Description = "يعتمد على تناول البقوليات و المكسرات و الأوراق الخضراء ,مفيد لمرضى السكر و القلب ",
                            Price = 19.989999999999998,
                            Title = " اختبار "
                        },
                        new
                        {
                            Id = "11",
                            CategoryId = "1",
                            Description = "يعتمد على تناول البقوليات و المكسرات و الأوراق الخضراء ,مفيد لمرضى السكر و القلب ",
                            Price = 19.989999999999998,
                            Title = " اختبار "
                        },
                        new
                        {
                            Id = "21",
                            CategoryId = "4",
                            Price = 20.0,
                            Title = "طقم اوزان دمبل 30 كغم"
                        },
                        new
                        {
                            Id = "22",
                            CategoryId = "4",
                            Price = 30.0,
                            Title = "حلقات لايف اب الاولمبية للجمباز"
                        },
                        new
                        {
                            Id = "23",
                            CategoryId = "4",
                            Price = 1490.0,
                            Title = "مشاية كهربائية منحنية بدون محرك"
                        },
                        new
                        {
                            Id = "24",
                            CategoryId = "4",
                            Price = 320.0,
                            Title = "دراجة سبينر"
                        },
                        new
                        {
                            Id = "25",
                            CategoryId = "4",
                            Price = 150.0,
                            Title = "Livepro أيروبيك ستيبر ومقعد"
                        },
                        new
                        {
                            Id = "26",
                            CategoryId = "4",
                            Price = 15.0,
                            Title = "سجادة Liveup للتمارين الرياضية"
                        },
                        new
                        {
                            Id = "27",
                            CategoryId = "4",
                            Price = 175.0,
                            Title = "مقعد بووفليكس متعدد الوظائف"
                        },
                        new
                        {
                            Id = "28",
                            CategoryId = "4",
                            Price = 69.0,
                            Title = "حبل معركة بروبانتل"
                        },
                        new
                        {
                            Id = "29",
                            CategoryId = "4",
                            Price = 125.0,
                            Title = "مقعد قابل للطي قابل للتعديل للتمارين الرياضية"
                        },
                        new
                        {
                            Id = "30",
                            CategoryId = "4",
                            Price = 25.0,
                            Title = "مجدّف"
                        },
                        new
                        {
                            Id = "31",
                            CategoryId = "3",
                            Price = 111.0,
                            Title = "زيت السمك أوميغا 3"
                        },
                        new
                        {
                            Id = "32",
                            CategoryId = "3",
                            Price = 78.0,
                            Title = "Muscletech, بلاتينيوم ملتي فيتامين"
                        },
                        new
                        {
                            Id = "33",
                            CategoryId = "3",
                            Price = 169.0,
                            Title = "Ultima Replenisher"
                        },
                        new
                        {
                            Id = "34",
                            CategoryId = "3",
                            Price = 169.0,
                            Title = "زيت الكريل"
                        },
                        new
                        {
                            Id = "35",
                            CategoryId = "3",
                            Price = 170.0,
                            Title = "أنافيت"
                        },
                        new
                        {
                            Id = "36",
                            CategoryId = "3",
                            Price = 79.0,
                            Title = "Trace Minerals Research"
                        },
                        new
                        {
                            Id = "37",
                            CategoryId = "3",
                            Price = 109.0,
                            Title = "BodyBio, E-Lyte"
                        },
                        new
                        {
                            Id = "38",
                            CategoryId = "3",
                            Price = 163.0,
                            Title = "فيجا ، سبورت"
                        },
                        new
                        {
                            Id = "39",
                            CategoryId = "3",
                            Price = 111.0,
                            Title = "مضاعف الترطيب"
                        },
                        new
                        {
                            Id = "40",
                            CategoryId = "3",
                            Price = 54.0,
                            Title = "NutriBiotic"
                        },
                        new
                        {
                            Id = "41",
                            CategoryId = "3",
                            Price = 169.0,
                            Title = "زيت الكريل"
                        });
                });

            modelBuilder.Entity("liaqati_master.Models.SportsProgram", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BodyFocus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("TrainingType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TblSportsProgram");
                });

            modelBuilder.Entity("liaqati_master.Models.Trak", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("servicesId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("servicesId");

                    b.ToTable("Trak");
                });

            modelBuilder.Entity("liaqati_master.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Cover_photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Exp_Years")
                        .HasColumnType("int");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Photograph")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wieght")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Active = false,
                            Cover_photo = "sssssssssssssssa",
                            Exp_Years = 10,
                            Fname = "sssssssssssssss",
                            Gender = 1,
                            Height = 120,
                            Lname = "sssssssssssssss",
                            Photograph = "ssssssssssssssss",
                            Wieght = 120
                        });
                });

            modelBuilder.Entity("liaqati_master.Models.Achievements", b =>
                {
                    b.HasOne("liaqati_master.Models.User", "User")
                        .WithMany("Achievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("liaqati_master.Models.Article", b =>
                {
                    b.HasOne("liaqati_master.Models.Category", "Category")
                        .WithMany("articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("liaqati_master.Models.ChatUser", b =>
                {
                    b.HasOne("liaqati_master.Models.Chat", "Chat")
                        .WithMany("ChatUser")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("liaqati_master.Models.User", "User")
                        .WithMany("ChatUser")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("liaqati_master.Models.Comment_Servies", b =>
                {
                    b.HasOne("liaqati_master.Models.Service", "services")
                        .WithMany("commentServies")
                        .HasForeignKey("servicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("services");
                });

            modelBuilder.Entity("liaqati_master.Models.Comments", b =>
                {
                    b.HasOne("liaqati_master.Models.Article", "articles")
                        .WithMany("comments")
                        .HasForeignKey("articlesId");

                    b.Navigation("articles");
                });

            modelBuilder.Entity("liaqati_master.Models.Exercies_program", b =>
                {
                    b.HasOne("liaqati_master.Models.Exercise", "exercise")
                        .WithMany("exercies_Programs")
                        .HasForeignKey("exerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("liaqati_master.Models.SportsProgram", "sportsProgram")
                        .WithMany("exercies_Programs")
                        .HasForeignKey("sportsProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("exercise");

                    b.Navigation("sportsProgram");
                });

            modelBuilder.Entity("liaqati_master.Models.Favorite_Servies", b =>
                {
                    b.HasOne("liaqati_master.Models.Favorite", "favorite")
                        .WithMany("Favorite_Servies")
                        .HasForeignKey("favoriteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("liaqati_master.Models.Service", "services")
                        .WithMany("favorites")
                        .HasForeignKey("servicesId1");

                    b.Navigation("favorite");

                    b.Navigation("services");
                });

            modelBuilder.Entity("liaqati_master.Models.HealthyRecipes", b =>
                {
                    b.HasOne("liaqati_master.Models.Service", "services")
                        .WithOne("HealthyRecipes")
                        .HasForeignKey("liaqati_master.Models.HealthyRecipes", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("services");
                });

            modelBuilder.Entity("liaqati_master.Models.MealPlans", b =>
                {
                    b.HasOne("liaqati_master.Models.Service", "services")
                        .WithOne("MealPlans")
                        .HasForeignKey("liaqati_master.Models.MealPlans", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("services");
                });

            modelBuilder.Entity("liaqati_master.Models.Message", b =>
                {
                    b.HasOne("liaqati_master.Models.Chat", "Chat")
                        .WithMany("Message")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("liaqati_master.Models.Order", b =>
                {
                    b.HasOne("liaqati_master.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("liaqati_master.Models.Order_Details", b =>
                {
                    b.HasOne("liaqati_master.Models.Service", "Service")
                        .WithMany("Order_Details")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("liaqati_master.Models.Order", "Order")
                        .WithMany("Order_Details")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("liaqati_master.Models.Products", b =>
                {
                    b.HasOne("liaqati_master.Models.Service", "services")
                        .WithOne("Products")
                        .HasForeignKey("liaqati_master.Models.Products", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("services");
                });

            modelBuilder.Entity("liaqati_master.Models.Rate", b =>
                {
                    b.HasOne("liaqati_master.Models.Order_Details", "Order_Details")
                        .WithOne("Rate")
                        .HasForeignKey("liaqati_master.Models.Rate", "Order_DetailsId");

                    b.Navigation("Order_Details");
                });

            modelBuilder.Entity("liaqati_master.Models.Service", b =>
                {
                    b.HasOne("liaqati_master.Models.Category", "Category")
                        .WithMany("services")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("liaqati_master.Models.SportsProgram", b =>
                {
                    b.HasOne("liaqati_master.Models.Service", "services")
                        .WithOne("sportsProgram")
                        .HasForeignKey("liaqati_master.Models.SportsProgram", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("services");
                });

            modelBuilder.Entity("liaqati_master.Models.Trak", b =>
                {
                    b.HasOne("liaqati_master.Models.Service", "services")
                        .WithMany("traks")
                        .HasForeignKey("servicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("services");
                });

            modelBuilder.Entity("liaqati_master.Models.Article", b =>
                {
                    b.Navigation("comments");
                });

            modelBuilder.Entity("liaqati_master.Models.Category", b =>
                {
                    b.Navigation("articles");

                    b.Navigation("services");
                });

            modelBuilder.Entity("liaqati_master.Models.Chat", b =>
                {
                    b.Navigation("ChatUser");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("liaqati_master.Models.Exercise", b =>
                {
                    b.Navigation("exercies_Programs");
                });

            modelBuilder.Entity("liaqati_master.Models.Favorite", b =>
                {
                    b.Navigation("Favorite_Servies");
                });

            modelBuilder.Entity("liaqati_master.Models.Order", b =>
                {
                    b.Navigation("Order_Details");
                });

            modelBuilder.Entity("liaqati_master.Models.Order_Details", b =>
                {
                    b.Navigation("Rate");
                });

            modelBuilder.Entity("liaqati_master.Models.Service", b =>
                {
                    b.Navigation("HealthyRecipes");

                    b.Navigation("MealPlans");

                    b.Navigation("Order_Details");

                    b.Navigation("Products");

                    b.Navigation("commentServies");

                    b.Navigation("favorites");

                    b.Navigation("sportsProgram");

                    b.Navigation("traks");
                });

            modelBuilder.Entity("liaqati_master.Models.SportsProgram", b =>
                {
                    b.Navigation("exercies_Programs");
                });

            modelBuilder.Entity("liaqati_master.Models.User", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("ChatUser");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
