# For more info on HTTP files go to https://aka.ms/vs/httpfile

@BaseUrl=https://localhost:7232
### 
GET {{BaseUrl}}/api/ArticlesApi/GetArticlesWithLoadMore?page=2&size=4

###
GET {{BaseUrl}}/api/ProductApi/search?sortBy=MinPrice


